#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BluetoothKeyboard.Resource", IsApplication=true)]

namespace BluetoothKeyboard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int button1 = 2131099655;
			
			// aapt resource value: 0x7f060010
			public const int button10 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button11 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int button12 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int button13 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button14 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int button15 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int button16 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int button17 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int button18 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int button19 = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int button2 = 2131099656;
			
			// aapt resource value: 0x7f06001a
			public const int button20 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int button21 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int button22 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int button23 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int button24 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int button25 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int button26 = 2131099680;
			
			// aapt resource value: 0x7f060009
			public const int button3 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button4 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int button5 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button6 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button7 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int button8 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int button9 = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int button_scan = 2131099654;
			
			// aapt resource value: 0x7f060024
			public const int discoverable = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int editText1 = 2131099682;
			
			// aapt resource value: 0x7f060005
			public const int new_devices = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int paired_devices = 2131099651;
			
			// aapt resource value: 0x7f060023
			public const int scan = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int spacebar = 2131099681;
			
			// aapt resource value: 0x7f060000
			public const int title_left_text = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int title_new_devices = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int title_paired_devices = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int title_right_text = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_title = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int device_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int device_name = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int option_menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int bt_not_enabled_leaving = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int button_scan = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int connect = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int discoverable = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int none_found = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int none_paired = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int not_connected = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int scanning = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int select_device = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int title_other_devices = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int title_paired_devices = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
